### ISSUE TITLE
No Hreflang tags on homepage

### ISSUE THREAD

**Issue by Chrisi1321** [ZiZuu-store/zzSEOtk#43] opened 2016-03-04 11:20 UTC
Hi!
I have upgraded my store to 1.6.1.4 and installed the newest version of the module.
I don't know why but there are now no hreflang tags on the homepage.

It works for categories and products and cms.

https://www.aktiv-naturheilmittel.at/

Thanks

**Comment by ZiZuu-store** [comment] 2016-03-04 15:33
Hi,
  is there a translated version of the HP? .. You had the module work fine with a previous PS version?

**Comment by Chrisi1321** [comment] 2016-03-04 17:21
Hi!
Yes there is translated version of it.
If I remember correctly I have contacted you already a long time ago about the same issue, and you changed something to make it work...

**Comment by Chrisi1321** [comment] 2016-03-06 14:09
Hi

I have just realized that this issue right now is not related to the issue last time

**Comment by ZiZuu-store** [comment] 2016-03-23 15:51
@Chrisi1321 can you confirm that this issue is still present on last **release 1.2.0** ?

**Comment by ZiZuu-store** [comment] 2016-04-07 10:35
OK, I suppose the issue isn't here. closing

**Comment by Chrisi1321** [comment] 2016-04-08 10:07
Hi!
Sorry I was on holiday so I did not have the time to check it.
Unfortunately it still doesn't work with 1.2.1
Regards

**Comment by ZiZuu-store** [comment] 2016-04-08 10:19
Hi,
  I saw .. I have not the possibility to test a similar configuration (a multishop with more then 1 domain) .. can you provide some access for debugging and solve the issue?

Thanks

**Comment by Chrisi1321** [comment] 2016-04-08 10:23
Sure.... I will send you the details to info@ZiZuu.com

**Comment by ZiZuu-store** [comment] 2016-04-08 11:22
@Chrisi1321  thank you very much .. will work on the issue ASAP

**Comment by ZiZuu-store** [comment] 2016-04-08 14:29
I found the problem .. and fixed it. Some caching issues was confusing me :)

Thank you very much for your support @Chrisi1321 .. I'll release a new version of the module in a few hours, your version is already ok, but update when next release will be available

Closing

**Closed by ZiZuu-store** 2016-04-08 14:29 UTC
Labels: bug, _assigned, _working
